/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api;

import domain.ResponseType;
import domain.User;
import java.io.IOException;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.assertNull;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

class AppTest {

    private final Retrofit retrofit = new Retrofit.Builder()
            .baseUrl("http://localhost:8080/api/")
            .addConverterFactory(GsonConverterFactory.create())
            .build();
    private UserApi userApi;

    @BeforeEach
    public void setUp() throws IOException {
        userApi = retrofit.create(UserApi.class);
    }

    @AfterEach
    public void tearDown() throws IOException {

    }

    @Test
    public void testLogin() throws IOException {
        User user = new User();
        user.setEmail("admin@test.com");
        user.setPassword("admin");
        Response<ResponseType> getResponse = userApi.login(user).execute();
        assertThat(getResponse.code(), is(200));
        ResponseType response = getResponse.body();
        assertNull(response.getMessage());
        user.setPassword("ehffew");
        getResponse = userApi.login(user).execute();
        response = getResponse.body();
        assertNull(response.getResult());
    }
}
