/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package roster;

import dao.SQLiteDAO;

import java.io.File;
import java.sql.Connection;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;
import service.Server;

public class App {

    private static Jdbi JDBI;
    public static SQLiteDAO dao;

    public static void main(String[] args) {
        boolean doesDBExist = new File("SQLiteDB.db").exists();
        Connection connection = Database.initDatabase();
        if (connection != null) {
            JDBI = Jdbi.create(connection);
            JDBI.installPlugin(new SqlObjectPlugin());
            dao = getRosterDAO();
        }
        if (!doesDBExist) {
            Database.insertDefaultValues();
        }
        new Server().start();
    }

    public static SQLiteDAO getRosterDAO() {
        return JDBI.onDemand(SQLiteDAO.class);
    }

}
